services:
  db:
    container_name: db
    restart: always
    image: postgres:15.2-alpine
    volumes:
      - ./postgres/init.sql:/docker-entrypoint-initdb.d/init.sql
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=chess_club
    ports:
      - "5432:5432"

  api:
    depends_on:
      - db
    build: .
    ports:
      - "3000:3000"

volumes:
  postgres_data:
